### ISSUE TITLE
Unable to authenticate against Crowd from Sonarqube

### ISSUE THREAD

**Issue by murthy1979** [deepy/sonar-crowd#23]
We have Sonarqube installed on docker environment and are trying to authenticate users & groups against our Atlassian Crowd. We see the request is not reaching Crowd. 

The crowd add-on is installed and configuration details are provided in sonar.properties.

Sonarqube version: Version 6.7.6 LGPL
Any help is much appreciated

Thanks

**Comment by murthy1979** [comment]
Can you please provide any pointer to the issue.

thanks

**Comment by deepy** [comment]
@murthy1979 if the request is not reaching Crowd and you can see a notice in the log that the Crowd plugin is loaded then it sounds like either the details in sonar.properties (check that `crowd.url` contains the correct path, is it http://crowd-stage/ or http://crowd-stage/crowd?) might be incorrect or that there's a network issue preventing it from connecting.

If the properties are correct, can you exec into the container and try connecting with curl and see that Crowd responds?

**Comment by deepy** [comment]
Closing question with no response
