### ISSUE TITLE
Plugin does not start in SQ 8

### ISSUE THREAD

**Issue by vgalunov** [deepy/sonar-crowd#33]
Developer Edition Version 8.1 (build 31237)
Crowd INTEGRATION 2.1.3
Atlassian Crowd Version: 3.4.5

```
sonar.security.realm=Crowd
crowd.url=https://domain.com/crowd/
crowd.application=sonar_server
crowd.password=sonar_passw
sonar.security.localUsers=admin
sonar.authenticator.downcase=true
```
In the log has to be success or error notification from CrowdRealm.java.
But command gives me 0 lines
cat /opt/sonarqube/logs/* | grep -i realm

This one gives 1 line:
cat /opt/sonarqube/logs/* | grep -i crowd
INFO web[o.s.s.p.ServerPluginRepository] Deploy plugin Crowd / 2.1.3

As I undertood SQ sees the plugin but the fact that there is no CrowdRealm class object means that plugin is not able to start.

Is plugin really compatible with 8 SQ?

**Comment by deepy** [comment]
It's possible that it might not work with 8, the last version I tried was 7.9 but in the last release all the deprecations were addressed.
I'll try it on 8.2 and see if it works

**Comment by deepy** [comment]
@vgalunov it worked fine for me on 8.2 with crowd 3.4.5.
I installed the latest version from the marketplace, added the following to `conf/sonar.properties` and stopped and started the server.
```
sonar.security.realm=Crowd
crowd.url=http://illusionist.local:8095/crowd/
crowd.application=sonar
crowd.password=sonar
sonar.security.localUsers=admin,sonar
```

After that I could login to sonar with my crowd user

**Comment by vgalunov** [comment]
@deepy 

It does not work for me for some reason and it is not a config issue.

Because according to https://github.com/deepy/sonar-crowd/blob/master/src/main/java/org/sonar/plugins/crowd/CrowdRealm.java

if config correct I should see line 104 execution result:
LOG.info("Crowd configuration is valid, connection test successful.");

else any of these 106-110:
throw new SonarException("Unable to test connection to crowd", e);
throw new SonarException("Application name and password are incorrect", e);
throw new SonarException("The application is not permitted to perform the requested operation on the crowd server", e);

But as you can see in provided logs there is no any notifications from CrowdRealm class.
There is INFO level set in my SQ.

So I assume the plugin is not able to start
Probably I should not rely to LOGS, and try to find the reason somewhere else.

Can you advise me how to investigate it?

**Comment by deaamoflih** [comment]
@vgalunov 
Hi ,
 i have now exactly the same issue.. i have tried it also for the SQ versions 7.9+ and got the same problem:
crowd plugin 2.1.3 deployed but not started.
did you have already a way to fix this? 
i appreciate your answer..

**Comment by vgalunov** [comment]
@deaamoflih 
You need an active license.

**Comment by deaamoflih** [comment]
@vgalunov 
thanks a lot for your answer.
you mean i have to upgrade the SQ Version with an  active license ?
i use in my deployment a docker image , pulled from the official SQ repo in docker hub.
