### ISSUE TITLE
sonar-crowd with SSO

### ISSUE THREAD

**Issue by saguirre1** [deepy/sonar-crowd#34]
The installation I have of Crowd is integrated with
-JIRA
-Bamboo
-Confluence
-Bitbucket

through SSO.

Is it possible that when I login for example to JIRA (which by SSO also logs me in to Crowd) I will also be logged in to SonarQube?

Thanks.

**Comment by deepy** [comment]
There's currently no SSO support, there's #5 for tracking that, but unfortunately there's no ongoing work.
I did give it a try once and it doesn't seem like it'd be impossible to implement, there's a branch called `sso-identity` if you're interested in trying to get it working.
