### ISSUE TITLE
licensing question

### ISSUE THREAD

**Issue by chrissike** [deepy/sonar-crowd#35]
Dear owner,
I can't find any licensing information in this repository. 
Could you please tell me if the content falls under an OS license?
Otherwise I will assume it's proprietary as discussed here: 
https://opensource.stackexchange.com/questions/1720/what-can-i-assume-if-a-publicly-published-project-has-no-license

Thank you very much for your response!
BR Christina

**Comment by deepy** [comment]
Hi @chrissike, it might be a bit confusing as the licensing details are in `pom.xml`, I'll extract them later tonight into a LICENSE.txt to make it easier, thanks for bringing this to attention!

**Comment by chrissike** [comment]
awesome @deepy, thank you very much for your fast reply!

**Comment by deepy** [comment]
Got a bit delayed, but now there's also a `LICENSE.txt`, thanks once again!
