### ISSUE TITLE
JAVA 11 on SQ leads to Exeption

### ISSUE THREAD

**Issue by derhecht** [deepy/sonar-crowd#36]
I'm working on the https://github.com/deepy/sonar-crowd/issues/5 but when loading plugin into SQ 7.9 running on JAVA 11 (in official Docker container) I got 
Caused by: java.lang.ClassNotFoundException: com.sun.xml.internal.bind.v2.ContextFactory
from
        at javax.xml.bind.JAXB.unmarshal(JAXB.java:241)
        at com.atlassian.crowd.integration.rest.service.RestExecutor$MethodExecutor.andReceive(RestExecutor.java:349)
        at com.atlassian.crowd.integration.rest.service.RestCrowdClient.findUserFromSSOToken(RestCrowdClient.java:859)
        at org.sonar.plugins.crowd.CrowdSsoIdentityProvider.init(CrowdSsoIdentityProvider.java:78)

Even with the newest Crowd plugin version they obviously do not remove the JAXB usage.

I merged your latest master code (to include the JAVA 11 commits) also but this does not solve the problem.

Any ideas? It looks like the plugin is not JAVA 11 compatible regarding SQ running on JAVA 11 at all.

**Comment by deepy** [comment]
Hmm, that's strange, I could've sworn there's reports of people running it on 7.9 and I'm pretty sure I tested it on Java 11
I currently don't have access to the correct laptop but I might be able to have a look at it tomorrow

Maybe there's an --add-module or similar necessary?

**Comment by deepy** [comment]
I don't have the testbed set up on that computer either.

So just to confirm some things, this is failing with a version you built from latest master (or a branch including latest master)?
Do you know if it works with the sonar-crowd from marketplace? That JAR can also be retrieved from https://github.com/deepy/sonar-crowd/releases/tag/2.1.3

I'm temporarily stuck out of town with the wrong laptop, but if the marketplace version does not work I can put some time into setting up a new test environment and see if I can reproduce the issue.

**Comment by derhecht** [comment]
I use the branch an merged master.

It works with 2.1.3 in JAVA 11 SonarQube 7.9.2 - so no problem on current marketplace version.

**Comment by deepy** [comment]
That's strange, the only thing different between 2.1.3 and master is that the license has been copied into LICENSE.txt, so something is strange, the branch I tried it on doesn't have anything that should impact it, so my best suggestion is try rebasing the branch on master instead of merging.
