### ISSUE TITLE
Problems with integration to internal crowd directories

### ISSUE THREAD

**Issue by cmillaqueo** [deepy/sonar-crowd#37]
We have problems to be able to synchronize the internal directories from crowd to sonarqube, only the directory that we have integrated into Ldap works correctly.

Some months ago we have upgrated sonar to its version 7.9.1, since then we have such a problem.

Our current sonar.properties configuration is as follows:

sonar.security.realm=Crowd

crowd.url=http://xx.xx.xx.xx:8080/crowd/

crowd.application=sonar_crowd

crowd.password=xxxxxx

crowd.groups.sync=true

sonar.authenticator.createUsers=true

sonar.security.updateUserAttributes=true

Currently our integrated tools are sonarqube 7.9.1 Enterprise, crowd 4.1.0 and the plugin for crowd is 2.1.3

Could you tell us if it is necessary to add any additional parameters?

Regards

**Comment by deepy** [comment]
Hmm, that's strange. I think my own testing relied mostly on internal directories.
And the point of Crowd is kinda that it shouldn't make a difference for the application querying for users.

Do your internal users have email addresses added to them?

**Comment by cmillaqueo** [comment]
Hi,

Yes, but a generic email is used for most of the users.

Regards.

**Comment by cmillaqueo** [comment]
Hi,

thanks you for the answer, i will try.

Regards

**Comment by cmillaqueo** [comment]
Hi,

indeed, that is the problem, I have done some tests and it has worked correctly.

Thanks a lot

Regards
