### ISSUE TITLE
Plugin doesn't work with SonarQube 8.9 LTS

### ISSUE THREAD

**Issue by madhuvanthiyellur** [deepy/sonar-crowd#42]
Hi,

We use Crowd as the primary authentication tool for SonarQube and we see that the plugin seems to be not working for newly released 8.9 LTS. SonarQube and Crowd connection is successful but unable to access Sonarqube. Is this issue known? Could you please fix this issue or give an update on when this will be done?

`INFO  web[][org.sonar.INFO] Security realm: Crowd
INFO  web[][c.a.c.s.c.ClientPropertiesImpl] Loading property: 'application.name' : 'sonarqube'
INFO  web[][c.a.c.s.c.ClientPropertiesImpl] Failed to find value for property: application.login.url
INFO  web[][c.a.c.s.c.ClientPropertiesImpl] Loading property: 'session.tokenkey' : 'session.tokenkey'
INFO  web[][c.a.c.s.c.ClientPropertiesImpl] Loading property: 'session.lastvalidation' : 'session.lastvalidation'
INFO  web[][c.a.c.s.c.ClientPropertiesImpl] Loading property: 'session.validationinterval' : '1'
INFO  web[][c.a.c.s.c.ClientPropertiesImpl] Failed to find value for property: cookie.domain
INFO  web[][o.s.p.c.CrowdRealm] Crowd configuration is valid, connection test successful.
INFO  web[][org.sonar.INFO] Security realm started`

P.S. The groups on crowd and Sonarqube are synced in our previous SQ versions.

Thank you!

**Comment by deepy** [comment]
Latest release on github has support for 8.9+ and I also verified that groups sync

Just waiting for https://github.com/SonarSource/sonar-update-center-properties/pull/229 to get completed and then it should show up in the update center

**Comment by deepy** [comment]
Feel free to grab the latest release from github, it should work with 8.9
