### ISSUE TITLE
map groups from crowd

### ISSUE THREAD

**Issue by carlobongiovanni** [deepy/sonar-crowd#6]
Hi, 
is it possible to use this plugin to map groups from crowd to sonar?

So for example I have in crowd groups called:
* sonar-administrators
* sonar-qualitygates
* sonar-etc

and I would like to map those groups with groups in sonar. Reading the wiki I understand is possible, but I could not find any description of how to configure them.

Thanks

**Comment by netropic** [comment]
I am also having problems getting Crowd (2.7.2) groups pulled into Sonar (5.6.4).

Furthermore, If i add a user to sonar-administrators in SonarQube, this group is removed when they log in, even if they are a member of sonar-administrators in Crowd.

**Comment by wysockip** [comment]
I have the same problem, can't get the groups pulled into Sonar. Anyone can take a look on that?

**Comment by wermut** [comment]
The workaround described in [#9](https://github.com/SonarQubeCommunity/sonar-crowd/issues/9) will also work for this one.

**Comment by deepy** [comment]
When testing 2.1 the groups are being mapped from crowd, I set myself as a member of sonar-administrators and it appeared just fine in sonar
